name: infra

on:
  workflow_dispatch:

permissions:
  id-token: write   # required for OIDC auth
  contents: read    # required to perform a checkout

jobs:
  provision-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Provision infrastructure
        uses: pulumi/actions@v6
        id: pulumi
        with:
          command: up
          stack-name: bdxio2024/dev
          work-dir: infra
        env:
          ARM_USE_OIDC: true
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}